export enum EmailType {
    THANK_YOU_FOR_SIGNING_UP = "THANK_YOU_FOR_SIGNING_UP",
    PURCHASED_SUBSCRIPTION = "PURCHASED_SUBSCRIPTION",
    CANCELLED_SUBSCRIPTION = "CANCELLED_SUBSCRIPTION",
    FREE_TRIAL_EXPIRES_SOON = "FREE_TRIAL_EXPIRES_SOON",
    FREE_TRIAL_EXPIRED = "FREE_TRIAL_EXPIRED",
    DELETED_USER = "DELETED_USER",
}
