export enum EmailType {
    WELCOME_TO_SAAS_NAME = "WELCOME_TO_SAAS_NAME",
    FREE_TRIAL_STARTED = "FREE_TRIAL_STARTED",
    FREE_TRIAL_EXPIRES_SOON = "FREE_TRIAL_EXPIRES_SOON",
    CANCELLED_SUBSCRIPTION = "CANCELLED_SUBSCRIPTION",
    DOWNGRADED_TO_FREE_PLAN = "DOWNGRADED_TO_FREE_PLAN",
}
