export const TextConstants = {
    TEXT__COMPANY_TITLE: "2mrw",
    TEXT__FIRST_NAME_PLACEHOLDER: "Timo",
    TEXT__EMAIL_PLACEHOLDER: "m@example.com",
    TEXT__LOGOUT: "Logout",
    TEXT__LOGOUT_SUCCESSFUL: "Logout successful!",
    TEXT__REDIRECTING_TO_GOOGLE: "Redirecting to Google...",
    TEXT__OR: "or",
    TEXT__SIGN_UP_EMAIIL_OR_ANOTHER_SERVICE: "Sign up using email or another service to continue!",
    TEXT__SIGN_IN_EMAIL_OR_ANOTHER_SERVICE: "Sign in using email or another service to continue!",
    TEXT__SIGN_UP: "Sign Up",
    TEXT__SIGN_IN: "Log In",
    TEXT__LOGIN_WITH_MAGIC_LINK: "Login with Magic Link",
    TEXT__INVALID_CREDENTIALS:
        "Hmm, those login details don't match our records. Please check them.",
    TEXT__USER_DOES_NOT_EXIST: "Hmm, we couldn't find a user with that email address.",
    TEXT__FREE: "Free",
    TEXT__MONTHLY: "Monthly",
    TEXT__YEARLY: "Yearly",
    TEXT__SUCCESS_USER_CREATED: "User has been created!",
    TEXT__HAVE_AN_ACCOUNT: "Have an account?",
    TEXT__FLEXIBLE_CANCELLATION: "Flexible cancellation, no strings attached.",
    TEXT__DO_NOT_HAVE_AN_ACCOUNT: "Don't have an account?",
    TEXT__CURRENT_PLAN: "Current Plan",
    TEXT__CHANGE_PLAN: "Change Plan",
    TEXT__UPGRADE_PLAN: "Upgrade Plan",
    TEXT__UNLOCK_FREE_PLAN: "Unlock Free Plan",
    TEXT__UNLOCK: "Unlock",
    TEXT__UNLOCK_PLAN: "Unlock Plan",
    TEXT__DOWNGRADE_TO_FREE_PLAN: "Downgrade To Free Plan",
    TEXT__DAYS: "Days",
    TEXT__MOST_POPULAR_OPTION: "Most Popular Option",
    TEXT__ENTER_EMAIL_BELOW:
        "Enter Your email address below and we'll send You a link to reset Your password.",
    TEXT__SEND_RESET_LINK: "Send Reset Link",
    TEXT__REMEMBER_PASSWORD: "Remember password?",
    TEXT__CONFIRM_SUBSCRIPTION_CHANGE: "Confirm Subscription Change",
    TEXT__RESENDING_EMAIL: "Resending Email...",
    TEXT__NEW_PASSWORD: "New Password",
    TEXT__CONTINUE: "Continue",
    TEXT__SUBSCRIPTION_CONFIRMED: "Subscription Confirmed!",
    TEXT__CONFIRM_PASSWORD: "Confirm New Password",
    TEXT__CONFIRM: "Confirm",
    TEXT__UPDATING: "Updating...",
    TEXT__UPDATE_PASSWORD: "Update Password",
    TEXT__ENTER_PASSWORD_BELOW: "Enter Your new password below to update Your account.",
    TEXT__SIGNING_IN: "Signing in...",
    TEXT__SIGNING_UP: "Signing up...",
    TEXT__SIGN_IN_SUCCESSFUL: "You've been logged in!",
    TEXT__MAGIC_LINK_SENT:
        "Magic link sent! Check your email inbox to continue signing in securely.",
    TEXT__SIGN_UP_SUCCESSFUL_CHECK_EMAIL: "Sign up successful! Please check email inbox.",
    TEXT__PASSWORD_HAS_BEEN_UPDATED: "Your password has been updated",
    TEXT__RESET_PASSWORD_EMAIL_SENT: "Success! Password reset email has been sent",
    TEXT__PLEASE_ENTER_AN_EMAIL: "Please enter an email address.",
    TEXT__CONFIRMATION_EMAIL_SENT: "Confirmation email has been sent",
    TEXT__HAS_SIX_PLUS_CHARACTERS: "Has 6+ characters",
    TEXT__HAS_ONE_LOWER_CASE_LETTER: "Has at least one lowercase letter",
    TEXT__HAS_ONE_UPPER_CASE_LETTER: "Has at least one uppercase letter",
    TEXT__HAS_ONE_DIGIT: "Has at least one digit",
    TEXT__SIGNUP_CONFIRMATION_SENT:
        "Sign up successful! Check your email inbox to confirm your account.",
    TEXT__DIDNT_RECEIVE_EMAIL: "Didn't receive the email?",
    TEXT__RESEND_EMAIL: "Resend email",

    ERROR__UNEXPECTED_ERROR: "There has been an unexpected error.",
    ERROR__INVALID_EMAIL: "Invalid email address",
    ERROR__STRIPE_CHECKOUT:
        "Failed to initiate checkout process! Please contact us if the issue persists.",
    ERROR_SIGNING_OUT: "Error signing out",
    ERROR__FAILED_TO_RESEND_EMAIL: "Failed to resend email.",
    ERROR__EMAIL_IS_MISSING: "Email is missing",
    ERROR__PASSWORD_IS_MISSING: "Password is missing.",
    ERROR__FIRST_NAME_IS_MISSING: "First name is missing",
    ERROR__CONFIRMATION_PASSWORD_IS_MISSING: "Confirmation password is missing.",
    ERROR__PASSWORDS_DO_NOT_MATCH: "Passwords do not match.",
    ERROR__FAILED_TO_SEND_PASSWORD_RESET_EMAIL: "Failed to send password reset email.",
    ERROR__USER_CREATION_FAILED: "There has been an error during user creation.",
    ERROR__DURING_SIGN_UP: "There has been an error during sign up.",
    ERROR__EMAIL_LIMIT_REACHED: "Email rate limit has been reached.",
    ERROR__EMAIL_ALREADY_IN_USE: "This email is in use. Please log in to continue.",
};
