export const TextConstants = {
    TEXT__COMPANY_TITLE: "2mrw",
    TEXT__FIRST_NAME_PLACEHOLDER: "Timo",
    TEXT__EMAIL_PLACEHOLDER: "m@example.com",
    TEXT__LOGOUT: "Logout",
    TEXT__LOGOUT_SUCCESSFUL: "Logout successful!",
    TEXT__REDIRECTING_TO_GOOGLE: "Redirecting to Google...",
    TEXT__OR: "or",
    TEXT__SIGN_UP_EMAIIL_OR_ANOTHER_SERVICE: "Sign up using email or another service to continue!",
    TEXT__SIGN_IN_EMAIL_OR_ANOTHER_SERVICE: "Sign in using email or another service to continue!",
    TEXT__SIGN_UP: "Sign Up",
    TEXT__SIGN_IN: "Log In",
    TEXT__MONTHLY: "Monthly",
    TEXT__YEARLY: "Yearly",
    TEXT__HAVE_AN_ACCOUNT: "Have an account?",
    TEXT__FLEXIBLE_CANCELLATION: "Flexible cancellation, no strings attached.",
    TEXT__DO_NOT_HAVE_AN_ACCOUNT: "Don't have an account?",
    TEXT__FREE_TRIAL_STARTED: "Free Trial has been started",
    TEXT__CURRENT_PLAN: "Current Plan",
    TEXT__CHANGE_PLAN: "Change Plan",
    TEXT__UPGRADE_PLAN: "Upgrade Plan",
    TEXT__UNLOCK: "Unlock",
    TEXT__UNLOCK_PLAN: "Unlock Plan",
    TEXT__START_FREE_TRIAL: "Start Free Trial",
    TEXT__DAYS: "Days",
    TEXT__FREE_TRIAL_END_DATE: "Free Trial End Date",
    TEXT__MOST_POPULAR_OPTION: "Most Popular Option",
    TEXT__ENTER_EMAIL_BELOW:
        "Enter Your email address below and we'll send You a link to reset Your password.",
    TEXT__SENDING: "Sending",
    TEXT__SEND_RESET_LINK: "Send Reset Link",
    TEXT__REMEMBER_PASSWORD: "Remember password?",
    TEXT__RESENDING_EMAIL: "Resending Email...",
    TEXT__NEW_PASSWORD: "New Password",
    TEXT__CONFIRM_PASSWORD: "Confirm New Password",
    TEXT__UPDATING: "Updating...",
    TEXT__UPDATE_PASSWORD: "Update Password",
    TEXT__ENTER_PASSWORD_BELOW: "Enter Your new password below to update Your account.",
    TEXT__SIGNING_IN: "Signing in...",
    TEXT__SIGNING_UP: "Signing up...",
    TEXT__SIGN_IN_SUCCESSFUL: "Sign in successful!",
    TEXT__SIGN_UP_SUCCESSFUL_CHECK_EMAIL: "Sign up successful! Please check email inbox.",
    TEXT__PASSWORD_HAS_BEEN_UPDATED: "Password has been updated",
    TEXT__RESET_PASSWORD_EMAIL_SENT: "Password reset email has been sent.",
    TEXT__PLEASE_ENTER_AN_EMAIL: "Please enter an email address.",
    TEXT__CONFIRMATION_EMAIL_SENT: "Confirmation email has been sent.",
    TEXT__HAS_SIX_PLUS_CHARACTERS: "Has 6+ characters",
    TEXT__HAS_ONE_LOWER_CASE_LETTER: "Has at least one lowercase letter",
    TEXT__HAS_ONE_UPPER_CASE_LETTER: "Has at least one uppercase letter",
    TEXT__HAS_ONE_DIGIT: "Has at least one digit",

    ERROR__UNEXPECTED_ERROR: "There has been an unexpected error.",
    ERROR__STRIPE_CHECKOUT:
        "Failed to initiate checkout process! Please contact us if the issue persists.",
    ERROR_SIGNING_OUT: "Error signing out",
    ERROR__STARTING_FREE_TRIAL: "Error starting free trial",
    ERROR__FAILED_TO_RESEND_EMAIL: "Failed to resend email.",
    ERROR__EMAIL_IS_MISSING: "Email is missing.",
    ERROR__EMAIL_IS_MISSING_AT_SIGN: "Email is missing an '@'.",
    ERROR__PASSWORD_IS_MISSING: "Password is missing.",
    ERROR__FIRST_NAME_IS_MISSING: "First name is missing.",
    ERROR__CONFIRMATION_PASSWORD_IS_MISSING: "Confirmation password is missing.",
    ERROR__PASSWORDS_DO_NOT_MATCH: "Passwords do not match.",
    ERROR__FAILED_TO_SEND_PASSWORD_RESET_EMAIL: "Failed to send password reset email.",
    ERROR__USER_CREATION_FAILED: "User creation failed.",
    ERRROR__DURING_SIGN_UP: "There has been an error during sign up.",
    ERROR__EMAIL_LIMIT_REACHED: "Email rate limit has been reached.",
    ERROR__EMAIL_ALREADY_IN_USE: "This email is in use. Please log in to continue.",
};
