import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className="h-full bg-white" lang="en">
            <body className={`h-full ${inter.className}`}>
                {children}
                <Toaster position="top-center" richColors closeButton />
            </body>
        </html>
    );
}
