import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html className="h-full bg-white" lang="en">
            <body className={`h-full ${inter.className}`}>
                {children}
                <Toaster position="top-left" />
            </body>
        </html>
    );
}
